// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdORYpYZ3uSSYkTkfOOlUt1t64mUS5r7Q',
    appId: '1:815165511973:web:b845ece09f514cd6e8a2cc',
    messagingSenderId: '815165511973',
    projectId: 'weddinghall-8a1f2',
    authDomain: 'weddinghall-8a1f2.firebaseapp.com',
    storageBucket: 'weddinghall-8a1f2.firebasestorage.app',
    measurementId: 'G-4Z0LGT0T3M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADkA8RhIFu86AdR81f0uU_QxcPCNPO6pg',
    appId: '1:815165511973:android:c460058e4f5a5d6de8a2cc',
    messagingSenderId: '815165511973',
    projectId: 'weddinghall-8a1f2',
    storageBucket: 'weddinghall-8a1f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7aqfhXiIM9QnzgDXV7kCpKgZesMsuo0E',
    appId: '1:815165511973:ios:579480aa0ad5efc7e8a2cc',
    messagingSenderId: '815165511973',
    projectId: 'weddinghall-8a1f2',
    storageBucket: 'weddinghall-8a1f2.firebasestorage.app',
    iosBundleId: 'com.example.weddingHall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7aqfhXiIM9QnzgDXV7kCpKgZesMsuo0E',
    appId: '1:815165511973:ios:579480aa0ad5efc7e8a2cc',
    messagingSenderId: '815165511973',
    projectId: 'weddinghall-8a1f2',
    storageBucket: 'weddinghall-8a1f2.firebasestorage.app',
    iosBundleId: 'com.example.weddingHall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdORYpYZ3uSSYkTkfOOlUt1t64mUS5r7Q',
    appId: '1:815165511973:web:1e1232b9ae101095e8a2cc',
    messagingSenderId: '815165511973',
    projectId: 'weddinghall-8a1f2',
    authDomain: 'weddinghall-8a1f2.firebaseapp.com',
    storageBucket: 'weddinghall-8a1f2.firebasestorage.app',
    measurementId: 'G-VFGBFQ7DC8',
  );
}
